# Generated by Django 5.2.5 on 2025-08-21 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_area_options_area_created_area_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Davomat', 'verbose_name_plural': 'Davomat'},
        ),
        migrations.AlterModelOptions(
            name='submit',
            options={'verbose_name': 'Topshirma', 'verbose_name_plural': 'Topshirmalar'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Topshiriq', 'verbose_name_plural': 'Topshiriqlar'},
        ),
        migrations.RemoveField(
            model_name='area',
            name='coord5',
        ),
        migrations.RemoveField(
            model_name='area',
            name='coord6',
        ),
        migrations.RemoveField(
            model_name='area',
            name='coord7',
        ),
        migrations.RemoveField(
            model_name='area',
            name='coord8',
        ),
        migrations.AlterField(
            model_name='area',
            name='coord1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='coord2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='coord3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='coord4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.area', verbose_name='Joylashuv'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name="O'tgan vaqti"),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='image',
            field=models.ImageField(upload_to='images/attendances', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Talaba'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqti'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='file',
            field=models.FileField(upload_to='files/submits', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='point',
            field=models.IntegerField(default=5, verbose_name='Ball'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Talaba'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.task', verbose_name='Topshiriq'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsifi'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='task',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi"),
        ),
    ]
