# Generated by Django 5.2.5 on 2025-08-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_attendance_options_alter_submit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='coord1',
            field=models.CharField(max_length=100, verbose_name='Kordinata 1'),
        ),
        migrations.AlterField(
            model_name='area',
            name='coord2',
            field=models.CharField(max_length=100, verbose_name='Kordinata 2'),
        ),
        migrations.AlterField(
            model_name='area',
            name='coord3',
            field=models.CharField(max_length=100, verbose_name='Kordinata 3'),
        ),
        migrations.AlterField(
            model_name='area',
            name='coord4',
            field=models.CharField(max_length=100, verbose_name='Kordinata 4'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
