# Generated by Django 5.2.5 on 2025-10-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_area_coord1_alter_area_coord2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('marketing', 'Marketing'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('arrived', 'Kelgan'), ('late', 'Kech qolgan'), ('failed', 'Xatolik')], max_length=100, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Yuklangan'), ('marked', 'Baholangan'), ('rejected', 'Qaytarilgan')], max_length=100, verbose_name='Holati'),
        ),
    ]
