# Generated by Django 5.2.5 on 2025-10-16 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
