# Generated by Django 5.2.5 on 2025-10-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_group_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='course',
            new_name='level',
        ),
    ]
